CREATE TABLE EMPLEADO(
ID_EMPLEADO NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(100),
APP NVARCHAR2(100),
EDAD NUMBER,
TELEFONO NVARCHAR2(100),
ESTADO_CIVIL NUMBER
);

INSERT INTO EMPLEADO VALUES(1,'Miguel','Martinez',25,'2244885566',1);
INSERT INTO EMPLEADO VALUES(2,'Mariana','Perez',35,'2215478596',2);
INSERT INTO EMPLEADO VALUES(3,'Ricardo','Martinez',40,'1144995875',5);

select * from empleado;

SELECT 
ID_EMPLEADO ,
NOMBRE ,
APP ,
EDAD ,
(
CASE 
WHEN EDAD <= 25 THEN 'Joven'
WHEN EDAD BETWEEN 26 AND 35 THEN 'Maduro'
WHEN EDAD > 35 THEN 'Mayor'
ELSE 'Fuera de rango' END
)
DETALLE_EDAD,
TELEFONO ,
ESTADO_CIVIL,
(
CASE ESTADO_CIVIL
WHEN 1 THEN 'Soltero'
WHEN 2 THEN 'Casado'
WHEN 3 THEN 'Veudo'
WHEN 4 THEN 'Divorceado'
WHEN 5 THEN 'Union libre'
ELSE 'Sin valor' END
) DETALLE_EMPLEADO
FROM empleado;



---OTHER TABLE
CREATE TABLE REFRESCOS (
    ID_REFRESCO NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100),
    MARCA NUMBER,
    PRECIO NUMBER,
    SABOR NUMBER,
    CONTENIDO NUMBER,
    PAIS NVARCHAR2(100)
);
DROP TABLE REFRESCOS
--MARCA 1 COCA COLA, 2 PEPSI, 3 BIGCOLA
--SABOR 1 COLA, 2 NARANJA, 3 TORONJA, 4 MANZANA, 5 OTROS
INSERT INTO REFRESCOS VALUES (1,'Pepsi',2,15,1,600, 'Usa');
INSERT INTO REFRESCOS VALUES (2,'Mirinda',2,18,2,450, 'Usa');
INSERT INTO REFRESCOS VALUES (3,'Manzanita sol',1,10,4,1000, 'Ale');
INSERT INTO REFRESCOS VALUES (4,'Manzanita lift',2,11,4,1000, 'Usa');
INSERT INTO REFRESCOS VALUES (5,'7Up',1,10,3,450, 'Ale');
INSERT INTO REFRESCOS VALUES (6,'Big Cola',3,8,1,800, 'Usa');
INSERT INTO REFRESCOS VALUES (7,'Fanta',1,25,2,2000, 'Ale');
INSERT INTO REFRESCOS VALUES (8,'Big Citrus',3,18,3,1800, 'Usa');

SELECT * FROM REFRESCOS;
--MARCA 1 COCA COLA, 2 PEPSI, 3 BIGCOLA
--SABOR 1 COLA, 2 NARANJA, 3 TORONJA, 4 MANZANA, 5 OTROS
--1 Mostrar los registros con sus 2 case Marca y Sabor
SELECT r.*, 
(
CASE MARCA
WHEN 1 THEN 'COCA COLA'
WHEN 2 THEN 'PEPSI'
WHEN 3 THEN 'BIG COLA'
ELSE 'Marca no existe' END
) DETALLE_MARCA,
(
CASE SABOR
WHEN 1 THEN 'COLA'
WHEN 2 THEN 'NARANJA'
WHEN 3 THEN 'TORONJA'
WHEN 4 THEN 'MANZANA'
WHEN 5 THEN 'OTROS'
ELSE 'Sabor no definido' END
)DETALLE_SABOR
FROM REFRESCOS r;
--2 Contar cuantos refrescos tengo de Cada Marca
SELECT 
COUNT(MARCA) TOTAL_EXISTENCIA,  (
CASE MARCA
WHEN 1 THEN 'COCA COLA'
WHEN 2 THEN 'PEPSI'
WHEN 3 THEN 'BIG COLA'
ELSE 'Marca no existe' END
) NOMBRE_MARCA
FROM REFRESCOS GROUP BY MARCA;
--3 Buscar los refrescos que su Nombre empieze con una M
SELECT * FROM REFRESCOS WHERE NOMBRE LIKE 'M%';
--4 Agregar un Case a la consulta 1 donde el contenido si es 100 a 450 que diga "refresco pequeño si esta entre 451 y 1800 "refresco mediano" y arriba de 
-- 1801 "Refresco grande"
SELECT r.*, 
(
CASE MARCA
WHEN 1 THEN 'COCA COLA'
WHEN 2 THEN 'PEPSI'
WHEN 3 THEN 'BIG COLA'
ELSE 'Marca no existe' END
) DETALLE_MARCA,
(
CASE SABOR
WHEN 1 THEN 'COLA'
WHEN 2 THEN 'NARANJA'
WHEN 3 THEN 'TORONJA'
WHEN 4 THEN 'MANZANA'
WHEN 5 THEN 'OTROS'
ELSE 'Sabor no definido' END
)DETALLE_SABOR,
(
CASE 
WHEN r.CONTENIDO BETWEEN 100 AND 450 THEN 'Refresco pequeño'
WHEN r.CONTENIDO BETWEEN 451 AND 1800 THEN 'Refresco mediano'
WHEN r.CONTENIDO > 1800 THEN 'Refresco grande'
ELSE '---' END
)TAMANIO
FROM REFRESCOS r;
--5 Sacar el promedio de precio de los referscos que su Pais sea "Ale"
SELECT AVG(PRECIO) PROMEDIO FROM REFRESCOS WHERE PAIS = 'Ale';
-- 6 Sacar el precio mas alto de los refrescos
SELECT MAX(PRECIO) PRECIO_MAS_BAJO FROM REFRESCOS;
--7 Obtener el contenido mas bajo de los refrescos
SELECT MIN(CONTENIDO) CONTENDIDO_MAS_BAJO FROM REFRESCOS;


