--
create table PRODUCTO18(
    ID_PRODUCTO NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100),
    MARCA NVARCHAR2(100),
    PRECIO NUMBER,
    TIPO NVARCHAR2(100)
);


CREATE TABLE BIT_PRODUCTO18(
    ID_BIT NUMBER PRIMARY KEY,
    ID_PRODUCTO NUMBER,
    NOMBRE NVARCHAR2(100),
    MARCA NVARCHAR2(100),
    PRECIO NUMBER,
    TIPO NVARCHAR2(100),
    OLD_NOMBRE NVARCHAR2(100),
    OLD_MARCA NVARCHAR2(100),
    OLD_PRECIO NUMBER,
    OLD_TIPO NVARCHAR2(100),
    ACCION NVARCHAR2(100),
    USUARIO NVARCHAR2(100),
    FECHA DATE
);



--creacion de trigger
CREATE OR REPLACE TRIGGER INSERT_PRODUCTO18
AFTER INSERT ON PRODUCTO18
FOR EACH ROW
--DECLARACION DE VARIABLES
DECLARE
    ID_B INT;
    FECHA_R DATE;
    USUARIO VARCHAR(50);
    --ACCION
    BEGIN
    SELECT MAX(ID_BIT +1) INTO ID_B FROM BIT_PRODUCTO18;
    SELECT SYSDATE INTO FECHA_R FROM DUAL;
    SELECT USER INTO USUARIO FROM DAUL;
    
    --VALIDA EL ID
    IF(ID_B IS NULL) THEN
        ID_B := 1;
    END IF;
    
    INSERT INTO BIT_PRODUCTO18 VALUES(
        ID_B, 
        :NEW.ID_PRODUCTO, 
        :NEW.NOMBRE, 
        :NEW.MARCA, 
        :NEW.PRECIO, 
        :NEW.TIPO,
        NULL,
        NULL,
        NULL,
        NULL,
        'INSERT',
        USUARIO,
        FECHA_R);
    --FIN
    END;
    
INSERT INTO PRODUCTO18 VALUES(1,'Avena','Ckeer',23,'Alimento');
INSERT INTO PRODUCTO18 VALUES(2,'Jumex naranja','Jumex',40,'Jugos');
select * from  PRODUCTO18;
select * from  BIT_PRODUCTO18;





--creacion de trigger DELETE
CREATE OR REPLACE NONEDITIONABLE TRIGGER DELETE_PRODUCTO18
AFTER DELETE ON PRODUCTO18
FOR EACH ROW
--DECLARACION DE VARIABLES
DECLARE
    ID_B INT;
    FECHA_R DATE;
    USUARIO VARCHAR(50);
--ACCION
BEGIN
    SELECT MAX(ID_BIT +1) INTO ID_B FROM BIT_PRODUCTO18;
    SELECT SYSDATE INTO FECHA_R FROM DUAL;
    SELECT USER INTO USUARIO FROM DUAL;
    
    --VALIDA EL ID
    IF(ID_B IS NULL) THEN
        ID_B := 1;
    END IF;
    
    INSERT INTO BIT_PRODUCTO18 VALUES(
        ID_B, 
        :OLD.ID_PRODUCTO, 
        NULL,
        NULL,
        NULL,
        NULL,
        :OLD.NOMBRE, 
        :OLD.MARCA, 
        :OLD.PRECIO, 
        :OLD.TIPO,
        'DELETE',
        USUARIO,
        FECHA_R);
--FIN
END;
    
DELETE FROM PRODUCTO18 WHERE ID_PRODUCTO=1;

select * from  PRODUCTO18;
select * from  BIT_PRODUCTO18;






--creacion de trigger UPDATE
CREATE OR REPLACE NONEDITIONABLE TRIGGER UPDATE_PRODUCTO18
AFTER UPDATE ON PRODUCTO18
FOR EACH ROW
--DECLARACION DE VARIABLES
DECLARE
    ID_B INT;
    FECHA_R DATE;
    USUARIO VARCHAR(50);
--ACCION
BEGIN
    SELECT MAX(ID_BIT +1) INTO ID_B FROM BIT_PRODUCTO18;
    SELECT SYSDATE INTO FECHA_R FROM DUAL;
    SELECT USER INTO USUARIO FROM DUAL;
    
    --VALIDA EL ID
    IF(ID_B IS NULL) THEN
        ID_B := 1;
    END IF;
    
    INSERT INTO BIT_PRODUCTO18 VALUES(
        ID_B, 
        :OLD.ID_PRODUCTO, 
        :NEW.NOMBRE, 
        :NEW.MARCA, 
        :NEW.PRECIO, 
        :NEW.TIPO,
        :OLD.NOMBRE, 
        :OLD.MARCA, 
        :OLD.PRECIO, 
        :OLD.TIPO,
        'UPDATE',
        USUARIO,
        FECHA_R);
--FIN
END;


UPDATE PRODUCTO18 SET NOMBRE = 'jumex MANZANA' WHERE ID_PRODUCTO = 2;

select * from  PRODUCTO18;
select * from  BIT_PRODUCTO18;




--- ej
INSERT INTO PRODUCTO18 VALUES(3,'Avena','Ckeer',23,'Alimento');
INSERT INTO PRODUCTO18 VALUES(5,'Avena','Ckeer',23,'Alimento');

DELETE FROM PRODUCTO18 WHERE ID_PRODUCTO = 4;