--creacion de tablas
create table ALUMNOS18TR(
    ID_ALUMNO NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(100),
    CURP NVARCHAR2(100)
);


create table BITACORA_ALUMNOS18TR(
    ID_BITACORA NUMBER PRIMARY KEY,
    ALUMNO_ID NUMBER,
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(100),
    CURP NVARCHAR2(100),
    OLD_NOMBRE NVARCHAR2(100),
    OLD_APP NVARCHAR2(100),
    OLD_CURP NVARCHAR2(100),
    ACCION NVARCHAR2(100),
    USUARIO NVARCHAR2(100),
    FECHA DATE
);


---- TRIGGER CON MULTIPLES ACCIONES: INERT, DELETE, UPDATE
CREATE OR  REPLACE NONEDITIONABLE TRIGGER INSERT_UPDATE_DELETE_TO_ALUMNOS18TR
AFTER INSERT OR UPDATE OR DELETE ON ALUMNOS18TR
FOR EACH ROW
--DECLARACION DE VARIABLES
DECLARE
    ID_B INT;
    FECHA_R DATE;
    USUARIO VARCHAR(50);
    --ACCION
BEGIN
    SELECT MAX(ID_BITACORA +1) INTO ID_B FROM BITACORA_ALUMNOS18TR;
    SELECT SYSDATE INTO FECHA_R FROM DUAL;
    SELECT USER INTO USUARIO FROM DUAL;

    --VALIDA EL ID
    IF(ID_B IS NULL) THEN
        ID_B := 1;
    END IF;
    
    --VALIDA EL TIPO DE TRIGGER DISPARADO
    IF INSERTING THEN
        INSERT INTO BITACORA_ALUMNOS18TR VALUES(
            ID_B, 
            :NEW.ID_ALUMNO, 
            :NEW.NOMBRE,
            :NEW.APP ,
            :NEW.CURP,
            NULL,
            NULL,
            NULL,
            'INSERT',
            USUARIO,
            FECHA_R
        );
    END IF;
    IF DELETING THEN
        INSERT INTO BITACORA_ALUMNOS18TR VALUES(
            ID_B, 
            :OLD.ID_ALUMNO, 
            NULL,
            NULL ,
            NULL,
            :OLD.NOMBRE,
            :OLD.APP ,
            :OLD.CURP,
            'DELETE',
            USUARIO,
            FECHA_R
        );
    END IF;
    IF UPDATING THEN
        INSERT INTO BITACORA_ALUMNOS18TR VALUES(
            ID_B, 
            :OLD.ID_ALUMNO, 
            :NEW.NOMBRE,
            :NEW.APP ,
            :NEW.CURP,
            :OLD.NOMBRE,
            :OLD.APP ,
            :OLD.CURP,
            'UPDATE',
            USUARIO,
            FECHA_R
        );
    END IF;
--FIN
END;


INSERT INTO ALUMNOS18TR VALUES (1,'Jesus', 'Gonzalez', 'VIGJ34985SDF');
UPDATE ALUMNOS18TR SET NOMBRE = 'JESUS V' WHERE ID_ALUMNO = 1;
DELETE FROM ALUMNOS18TR WHERE ID_ALUMNO = 1;


INSERT INTO ALUMNOS18TR VALUES (2,'Jesus2', 'Gonzalez2', 'VIGJ34985SDF');
UPDATE ALUMNOS18TR SET NOMBRE = 'JESUS *****' WHERE ID_ALUMNO = 2;
DELETE FROM ALUMNOS18TR WHERE ID_ALUMNO = 2;

SELECT * FROM ALUMNOS18TR;
SELECT * FROM BITACORA_ALUMNOS18TR;