--creacion de tablas
create table AUTOS18TR(
    ID_AUTO number PRIMARY KEY,
    NOMBRE nvarchar2(100),
    MARCA nvarchar2(100),
    PRECIO number
);
--DROP TABLE autos18tr


create table BITACORA_AUTOS18TR(
    ID_BITACORA number primary key,
    AUTO_ID number,
    NOMBRE nvarchar2(100),
    MARCA nvarchar2(100),
    PRECIO number,
    OLD_NOMBRE nvarchar2(100),
    OLD_MARCA nvarchar2(100),
    OLD_PRECIO number,
    ACCION NVARCHAR2(100),
    USUARIO NVARCHAR2(100),
    FECHA DATE
);


---
create or replace NONEDITIONABLE TRIGGER INSERT_AUTOS18TR
AFTER INSERT ON AUTOS18TR
FOR EACH ROW
--DECLARACION DE VARIABLES
DECLARE
    ID_B INT;
    FECHA_R DATE;
    USUARIO VARCHAR(50);
    --ACCION
    BEGIN
    SELECT MAX(ID_BITACORA +1) INTO ID_B FROM BITACORA_AUTOS18TR;
    SELECT SYSDATE INTO FECHA_R FROM DUAL;
    SELECT USER INTO USUARIO FROM DUAL;

    --VALIDA EL ID
    IF(ID_B IS NULL) THEN
        ID_B := 1;
    END IF;

    INSERT INTO BITACORA_AUTOS18TR VALUES(
        ID_B, 
        :NEW.ID_AUTO, 
        :NEW.NOMBRE, 
        :NEW.MARCA, 
        :NEW.PRECIO,
        NULL,
        NULL,
        NULL,
        'INSERT',
        USUARIO,
        FECHA_R);
--FIN
END;


---- TRIGGER DELETE
create or replace NONEDITIONABLE TRIGGER DELETE_AUTOS18TR
AFTER DELETE ON AUTOS18TR
FOR EACH ROW
--DECLARACION DE VARIABLES
DECLARE
    ID_B INT;
    FECHA_R DATE;
    USUARIO VARCHAR(50);
    --ACCION
    BEGIN
    SELECT MAX(ID_BITACORA +1) INTO ID_B FROM BITACORA_AUTOS18TR;
    SELECT SYSDATE INTO FECHA_R FROM DUAL;
    SELECT USER INTO USUARIO FROM DUAL;

    --VALIDA EL ID
    IF(ID_B IS NULL) THEN
        ID_B := 1;
    END IF;

    INSERT INTO BITACORA_AUTOS18TR VALUES(
        ID_B, 
        :OLD.ID_AUTO, 
        NULL,
        NULL,
        NULL,
        :OLD.NOMBRE, 
        :OLD.MARCA, 
        :OLD.PRECIO,
        'DELETE',
        USUARIO,
        FECHA_R);
--FIN
END;




---- TRIGGER UPDATE
create or replace NONEDITIONABLE TRIGGER UPDATE_AUTOS18TR
AFTER UPDATE ON AUTOS18TR
FOR EACH ROW
--DECLARACION DE VARIABLES
DECLARE
    ID_B INT;
    FECHA_R DATE;
    USUARIO VARCHAR(50);
    --ACCION
    BEGIN
    SELECT MAX(ID_BITACORA +1) INTO ID_B FROM BITACORA_AUTOS18TR;
    SELECT SYSDATE INTO FECHA_R FROM DUAL;
    SELECT USER INTO USUARIO FROM DUAL;

    --VALIDA EL ID
    IF(ID_B IS NULL) THEN
        ID_B := 1;
    END IF;

    INSERT INTO BITACORA_AUTOS18TR VALUES(
        ID_B, 
        :NEW.ID_AUTO, 
        :NEW.NOMBRE, 
        :NEW.MARCA, 
        :NEW.PRECIO,
        :OLD.NOMBRE, 
        :OLD.MARCA, 
        :OLD.PRECIO,
        'UPDATE',
        USUARIO,
        FECHA_R);
--FIN
END;





insert into autos18tr values(1,'Volvo XC40', 'Volvo', 754000);
UPDATE AUTOS18TR SET NOMBRE = 'Volvo' WHERE ID_AUTO = 1;
DELETE FROM AUTOS18TR WHERE ID_AUTO = 1;
insert into autos18tr values(2,'GT', 'GM', 966000);
insert into autos18tr values(3,'Q3', 'AUDI', 105500);

SELECT * FROM AUTOS18TR;
SELECT * FROM BITACORA_AUTOS18TR;

